### PR TITLE
Refactor for v2.0.0

### LINKED ISSUE #11: more speed
Downloading BAMs could probably be a lot quicker:

https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/2811e622e48a1e2bd48e82b785b5b8635dd3b039/src/GATK_gCNVcaller.sh#L56-L59

looks to take ~20 minutes from a random job, could be rewritten as `echo ${bambais[@]} | xargs -n1 -P$(nproc --all) dx download --no-progress` and hopefully would be much faster

### LINKED ISSUE #12: non-optional / default input
input here should be non-optional or have a default, if not causes app to fail with unhelpful error: https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/2811e622e48a1e2bd48e82b785b5b8635dd3b039/resources/home/dnanexus/generate_gcnv_bed.py#L22

### LINKED ISSUE #13: prebuild packages to .whl files
would be better to prebuild the source packages for pyvcf, pysam and pybedtools as .whl files for Pyhton 3.8 as these are slow to install from when the app runs, this can be done with `pip wheel`

### PR DESCRIPTION
**Pull request by jethror1**
- refactor of app for v2.0.0 to allow scattering of CNV calling to sub jobs by chromosome
- split main function to separate functions by each step to run
- added parallel download / upload
  - fixes #11 
- tune some of the parallel process steps by setting differing limits
- update readme with inputs and examples
  - fixes #12 #17 #18 
- many other minor fixes and improvements
  - fixes #13 #16
- example WES run in ~2 1/2 hours: https://platform.dnanexus.com/panx/projects/Gj2jj604ByG4z4z5j0VzyX8P/monitor/job/GvkQzjQ4ByG2Pz86693gpB3k
- example CEN SP run in 34m: https://platform.dnanexus.com/panx/projects/Gj2jj604ByG4z4z5j0VzyX8P/monitor/job/Gvp7jQQ4ByG4k8gyZ7fxQbZP
- example CEN S1 run in 1h4m: https://platform.dnanexus.com/panx/projects/Gj2jj604ByG4z4z5j0VzyX8P/monitor/job/Gvp7KyQ4ByG8601kPK3gzFqy

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)

### CODE REVIEW

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Addy81, @chrispyatt, @Emma-MacK, and @Yu-jinKim)

___
*[`src/gatk_gcnv_caller.sh` line 262 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBeF0RABTeZqs5sz881:-OBeIgTZDTAbjLOa42UQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/src/gatk_gcnv_caller.sh#L262)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

gernline
</blockquote></details>

Done.

**Review by chrispyatt — APPROVED** [review]
> Reviewed 10 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: all files reviewed, 1 unresolved discussion (waiting on @Addy81, @Emma-MacK, and @Yu-jinKim)

**Review by Emma-MacK — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: all files reviewed, 4 unresolved discussions (waiting on @Addy81, @jethror1, and @Yu-jinKim)

___
*[`src/gatk_gcnv_caller.sh` line 214 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBaG0hS0gCo3fG3fxN_:-OBaG0hS0gCo3fG3fxNa:b-sy13kp) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/src/gatk_gcnv_caller.sh#L214)):*
> ```Shell
>     Call GATK FilterIntervals to filter out low coverage / non unique mapped regions
>     '''
>     mark-section "Running FilterIntervals for the preprocessed intervals with sample basecounts"
> ```

In previous script this was just mark-section "FilterIntervals" - do we need a long description in the mark-section commands?
___
*[`README.md` line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OB_xIYf9A0slS0MgtNR:-OB_xIYf9A0slS0MgtNS:bsqhzsc) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/README.md#L68)):*
> ```Markdown
>   -irun_name="<name of run>"
> ```
> ```

Could potentially include an example command here showing file IDs being used
___
*[`src/gatk_gcnv_caller.sh` line 509 at r2](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBf-cwqCeyYZziAddT-:-OBf-cwrD3SsD5-LHiuY:be1en7e) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/4b2b10e247befcd03732ddf0efb2fdca9c302d24/src/gatk_gcnv_caller.sh#L509)):*
> ```Shell
> _get_sub_job_output() {
>     : '''
>     Get the output of GerminelineCNVCaller run in each subjob and download back to the parent job.
> ```

GerminelineCNVCaller -> GermlineCNVCaller

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @Addy81, @chrispyatt, @Emma-MacK, and @Yu-jinKim)

___
*[`README.md` line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OB_xIYf9A0slS0MgtNR:-OBfBW_JCaQp_REb8MCe:bmmaojd) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/README.md#L68)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

Could potentially include an example command here showing file IDs being used
</blockquote></details>

have added a tip on how to generate the array of inputs into the readme
___
*[`src/gatk_gcnv_caller.sh` line 214 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBaG0hS0gCo3fG3fxN_:-OBfC1yP-VSV-qhU9qOj:b-hd6bcr) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/src/gatk_gcnv_caller.sh#L214)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

In previous script this was just mark-section "FilterIntervals" - do we need a long description in the mark-section commands?
</blockquote></details>

I ditched the separate `echo` and `mark-sections` to combine them into one line, and I also find it more useful too when something fails as previously it would have the error in the browser 
`Error while CollectReadCounts (please refer to the job log for more information). Warning: Out of memory error occurred during this job.`

 which is not good English, and now would be 
`Error while Running CollectReadCounts for all input bams (please refer to the job log for more information). Warning: Out of memory error occurred during this job.`
___
*[`src/gatk_gcnv_caller.sh` line 509 at r2](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBf-cwqCeyYZziAddT-:-OBfD0iSAT_wum-i9JZD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/4b2b10e247befcd03732ddf0efb2fdca9c302d24/src/gatk_gcnv_caller.sh#L509)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

GerminelineCNVCaller -> GermlineCNVCaller
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: all files reviewed, 3 unresolved discussions (waiting on @Addy81 and @Emma-MacK)

**Review by Emma-MacK — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Addy81)

___
*[`src/gatk_gcnv_caller.sh` line 214 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19#-OBaG0hS0gCo3fG3fxN_:-OBfE5_M9DV6fxH9HuwX:b-p87v17) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/8ba6d2a770fb4dfeca74d453bd7e0b86c41d49a1/src/gatk_gcnv_caller.sh#L214)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I ditched the separate `echo` and `mark-sections` to combine them into one line, and I also find it more useful too when something fails as previously it would have the error in the browser 
`Error while CollectReadCounts (please refer to the job log for more information). Warning: Out of memory error occurred during this job.`

 which is not good English, and now would be 
`Error while Running CollectReadCounts for all input bams (please refer to the job log for more information). Warning: Out of memory error occurred during this job.`
</blockquote></details>

That makes sense, thanks!

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
