### PR TITLE
Parallel calling

### LINKED ISSUE #12: non-optional / default input
input here should be non-optional or have a default, if not causes app to fail with unhelpful error: https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/2811e622e48a1e2bd48e82b785b5b8635dd3b039/resources/home/dnanexus/generate_gcnv_bed.py#L22

### PR DESCRIPTION
**Pull request by chrispyatt**
Changes to allow WES CNV calling.

- Bams & bais download in parallel. Addresses #11 
- New option "scatter" to run cnv calling in multiple subjobs
- Bump up timeout to 4h & instance type to x16
- Make run_name non-optional to fix #12 
- Variable references fixed in calls to parallel
- Step 4 (cnv calling) now scatters intervals & runs separate jobs if requested
- PostProcess step now uses batch input string to accommodate potential parallel call directories

Initial testing - https://platform.dnanexus.com/panx/projects/Gj2jj604ByG4z4z5j0VzyX8P/monitor

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)

### CODE REVIEW

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[`dxapp.json` line 187 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0IfXBB0Vo7kGX3q2Sp:-O0IfXBB0Vo7kGX3q2Sq:b-jbwwhv) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L187)):*
> ```JSON
>         "systemRequirements": {
>             "*": {
>             "instanceType": "mem2_ssd1_v2_x16"
> ```

decision to be made: this takes around 3.5h but can be reduced by ~40 mins if we bump up further to mem3_ssd1_v2_x32. Increases run cost from ~$25 to ~$30.
___
*[`src/GATK_gCNVcaller.sh` line 135 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Ig5IAD5ZrHgi3slL5:-O0Ig5IAD5ZrHgi3slL6:bmdvxdf) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L135)):*
> ```Shell
>             --INPUT /data/beds/filtered.interval_list \
>             --SUBDIVISION_MODE INTERVAL_COUNT \
>             --SCATTER_CONTENT 5000 \
> ```

should scatter_content (number of intervals per subjob) be an input to the app?
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Igk3hDpMXvMNaURyk:-O0Igk3hDpMXvMNaURyl:bfkt8ys) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L142)):*
> ```Shell
>         dx upload -rp /home/dnanexus/inputs/base_counts
>         # Call CNVs via subjobs on scattered intervals
>         cnv_call_jobs=()
> ```

scattering like this (rather than by chromosome) gives us n equal jobs (currently ~40 mins each) but testing needed to see how it handles cnvs that span the breakpoints.

Scattering by chromosome would negate this (if it's an issue) but means that the longest job (Chr1) would likely be around 1.5-2hrs so the whole run would take much longer.

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[`dxapp.json` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0JB-qF8-DQVLqRjSru:-O0JB-qF8-DQVLqRjSrv:bafu95j) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L6)):*
> ```JSON
>     "summary": "GATK gCNV germline CNV caller",
>     "dxapi": "1.0.0",
>     "version": "1.0.2",
> ```

1.1.0 or 2.0.0?

**Review by Addy81 — CHANGES_REQUESTED** [review]
Are we also taking this issue on board? Or add a comment if decision not to https://github.com/eastgenomics/eggd_GATKgCNV_call/issues/13

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-:-O0OREsy13uLwqW01hO3:bz0eeqb)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`dxapp.json` line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0JB-qF8-DQVLqRjSru:-O0ORtB37Mtz37dJPvti:bkdg900) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L6)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

1.1.0 or 2.0.0?
</blockquote></details>

I'm leaning towards 2, scatter feels like a bigger update. But can here arguments for 1.1.0
___
*[`dxapp.json` line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OZ6FQ49o9f6D3EQuP:-O0OZ6FQ49o9f6D3EQuQ:b-viu2lh) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L134)):*
> ```JSON
>         "optional": true,
>         "patterns": ["*.tsv"],
>         "help": "Probability of the copy number of the chromosomes"
> ```

could we have consistent help messages to calm my mind please? :dancer:  
___
*[`dxapp.json` line 180 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OTQCmENiilOl0KoTI:-O0OTQCmENiilOl0KoTJ:bf5v8gg) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L180)):*
> ```JSON
>         "project": "CONTRIBUTE",
>         "network": [
>         "*"
> ```

Do we need access to this?
___
*[`dxapp.json` line 187 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0IfXBB0Vo7kGX3q2Sp:-O0OSXL-DHzQHKqKypi2:bmhj8s5) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L187)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

decision to be made: this takes around 3.5h but can be reduced by ~40 mins if we bump up further to mem3_ssd1_v2_x32. Increases run cost from ~$25 to ~$30.
</blockquote></details>

is this considering the spliting by intervals instead of chromosomes?
___
*[`src/GATK_gCNVcaller.sh` line 60 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OU5h11KF94Y_LXJX3:-O0OU5h11KF94Y_LXJX4:bnz3dq5) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L60)):*
> ```Shell
>     echo ${bambais[@]} | jq -r '.["$dnanexus_link"]' | xargs -n1 -P$(nproc --all) dx download --no-progress -o bams/
> 
>     cd /home/dnanexus
> ```

do you need this line? if you have removed the cd above i think you are there.
___
*[`src/GATK_gCNVcaller.sh` line 135 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Ig5IAD5ZrHgi3slL5:-O0OUNoK3_V8ToR0SirU:bm4cei2) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L135)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

should scatter_content (number of intervals per subjob) be an input to the app?
</blockquote></details>

I think that makes sense.
___
*[`src/GATK_gCNVcaller.sh` line 143 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OV3g6A9tpmrQpWQ8b:-O0OV3g6A9tpmrQpWQ8c:b-xg3qri) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L143)):*
> ```Shell
>         # Call CNVs via subjobs on scattered intervals
>         cnv_call_jobs=()
>         for i in $( find /home/dnanexus/inputs/scatter-dir -name "scattered.interval_list" ); do
> ```

I'm assuming this is the output of IntervalListToos? Will it always be called this?
___
*[`src/GATK_gCNVcaller.sh` line 252 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OXonu9kMM1qQgQUss:-O0OXonv5ZDL6JrWgQn9:bbogjci) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L252)):*
> ```Shell
> call_cnvs() {
> 
>     dx-download-all-inputs --parallel
> ```

There's some jethro wisdom in case it speeds thigns up: 

Link; https://github.com/eastgenomics/eggd_tso500/blob/ae5633715754453ea8c001cc5b5f38434679330e/src/code.sh#L61
___
*[`src/GATK_gCNVcaller.sh` line 263 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OY0iK2QVjtUCoBMkD:-O0OY0iK2QVjtUCoBMkE:b-rsrvq4) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L263)):*
> ```Shell
>     mkdir -p /home/dnanexus/in/basecounts
>     dx download $( dx find data --project $DX_WORKSPACE_ID --name *hdf5 --brief )
>     mv *hdf5 /home/dnanexus/in/basecounts/
> ```

Could you add this directly to the download command?
___
*[`src/GATK_gCNVcaller.sh` line 268 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OY9Jc8Uz4cn5bgXbB:-O0OY9Jc8Uz4cn5bgXbC:bi2z8l5) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L268)):*
> ```Shell
>     mkdir ploidy-dir
>     dx download -r $DX_WORKSPACE_ID:ploidy-dir/ploidy-calls -o ploidy-dir/
>     mv ploidy-dir/ /home/dnanexus/in/
> ```

as above, could the ploidy directory be mkdir -p /home/dnanexus/in/ploidy-dir then download directly in there? 
How big are they files? Should it be parallelised at all?
___
*[`src/GATK_gCNVcaller.sh` line 297 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OYlgz2cwEDu9KWIBB:-O0OYlgz2cwEDu9KWIBC:ba2q49k) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L297)):*
> ```Shell
>     # Upload outputs back to parent (only upload those required for next steps)
>     mkdir -p out/GermlineCNVCaller/gCNV-dir
>     mv /home/dnanexus/in/gCNV-dir/$name-calls out/GermlineCNVCaller/gCNV-dir/
> ```

does this space here work?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @Addy81, @chrispyatt, and @mattgarner)

___
*[`dxapp.json` line 144 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PQM1T2dsz_vDptQLo:-O0PQM1T2dsz_vDptQLp:b73dmhf) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L144)):*
> ```JSON
>         }
>     ],
>     "runSpec": {
> ```

you can make the parent job always run as high priority so it can't be terminated by setting this in the `runSpec`:
 https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/dxapp.json#L247
___
*[`dxapp.json` line 187 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0IfXBB0Vo7kGX3q2Sp:-O0PQavk491uhkedBfIN:bwnk7p0) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L187)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

is this considering the spliting by intervals instead of chromosomes?
</blockquote></details>

I would add this to the top of the script and in your sub jobs to make it log the instance usage every 30 seconds (or more frequent) to get a better idea on CPU/memory usage for helping to choose the most optimal: https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/src/code.sh#L8
___
*[`src/GATK_gCNVcaller.sh` line 140 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PRhRwBWkfWPwit9gS:-O0PRhRwBWkfWPwit9gT:bxenx52) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L140)):*
> ```Shell
>         tsv=$( dx upload --brief /home/dnanexus/inputs/beds/annotated_intervals.tsv )
>         dx upload -rp /home/dnanexus/inputs/ploidy-dir
>         dx upload -rp /home/dnanexus/inputs/base_counts
> ```

do you know how many files there are between these 2 dirs? if it's a lot this will be fairly slow (adding a `time` before will give you some idea).

If it is I'd consider uploading in parallel with something like this if you need to keep the dir structure (adjusting the removing of `/home/dnanexus/out` as needed): https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/src/code.sh#L328

or if not then a `find /home/dnanexus/inputs/ploidy-dir -type f | xargs -n1 -P${THREADS} dx upload --no-progress` should work



_Code quote:_
```Shell
        dx upload -rp /home/dnanexus/inputs/ploidy-dir
        dx upload -rp /home/dnanexus/inputs/base_counts
```
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Igk3hDpMXvMNaURyk:-O0PR7gr0z0deqw7rfIx:bjhesey) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L142)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

scattering like this (rather than by chromosome) gives us n equal jobs (currently ~40 mins each) but testing needed to see how it handles cnvs that span the breakpoints.

Scattering by chromosome would negate this (if it's an issue) but means that the longest job (Chr1) would likely be around 1.5-2hrs so the whole run would take much longer.
</blockquote></details>

could you store a mapping of chromosome number to instance type to use and run calling for chr1 on a bigger instance if it would speed it up?

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 0 of 2 files reviewed, 12 unresolved discussions (waiting on @Addy81, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OZ6FQ49o9f6D3EQuP:-O0nCGmcC8qsYidgwJq9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L134)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

could we have consistent help messages to calm my mind please? :dancer:
</blockquote></details>

Done.
___
*[`dxapp.json` line 144 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PQM1T2dsz_vDptQLo:-O0nCG8c3mH06gt7sTDR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L144)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you can make the parent job always run as high priority so it can't be terminated by setting this in the `runSpec`:
 https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/dxapp.json#L247
</blockquote></details>

Done.
___
*[`dxapp.json` line 180 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OTQCmENiilOl0KoTI:-O0nCEJC8A5iLMXPWZYQ:ba3dfob) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L180)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Do we need access to this?
</blockquote></details>

Removed
___
*[`dxapp.json` line 187 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0IfXBB0Vo7kGX3q2Sp:-O0nC2k96GINd6SvLr4U:b-lsvvd4) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L187)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would add this to the top of the script and in your sub jobs to make it log the instance usage every 30 seconds (or more frequent) to get a better idea on CPU/memory usage for helping to choose the most optimal: https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/src/code.sh#L8
</blockquote></details>

The two figures are both for splitting evenly. I've added the usage check though so we can look at this again.
___
*[`src/GATK_gCNVcaller.sh` line 60 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OU5h11KF94Y_LXJX3:-O0nBwMD3Wq3ocxu1YdN:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L60)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

do you need this line? if you have removed the cd above i think you are there.
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 135 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Ig5IAD5ZrHgi3slL5:-O0nBuYi5CODJLyw60IS:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L135)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I think that makes sense.
</blockquote></details>

Done
___
*[`src/GATK_gCNVcaller.sh` line 140 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PRhRwBWkfWPwit9gS:-O0nBfkg5W8Vh3okiv0y:b47g5xp) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L140)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you know how many files there are between these 2 dirs? if it's a lot this will be fairly slow (adding a `time` before will give you some idea).

If it is I'd consider uploading in parallel with something like this if you need to keep the dir structure (adjusting the removing of `/home/dnanexus/out` as needed): https://github.com/eastgenomics/eggd_tso500/blob/317064f7ce2232925f267a71b2ec2aa2a2eed0dc/src/code.sh#L328

or if not then a `find /home/dnanexus/inputs/ploidy-dir -type f | xargs -n1 -P${THREADS} dx upload --no-progress` should work
</blockquote></details>

Not many files. It looks like the upload only takes a couple of minutes at most
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Igk3hDpMXvMNaURyk:-O0nBE9YBMWzhh294V1f:b-pflzg1) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could you store a mapping of chromosome number to instance type to use and run calling for chr1 on a bigger instance if it would speed it up?
</blockquote></details>

Deferring this until I've checked whether breakpoint spanning CNVs are affected
___
*[`src/GATK_gCNVcaller.sh` line 143 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OV3g6A9tpmrQpWQ8b:-O0nAfL68lhP47igYUyD:b-n65khb) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L143)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I'm assuming this is the output of IntervalListToos? Will it always be called this?
</blockquote></details>

The directory name is set in the scatter command so shouldn't change
___
*[`src/GATK_gCNVcaller.sh` line 252 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OXonu9kMM1qQgQUss:-O0nCKVMAkhcRbA7Z0n3:bz1lzu) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L252)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

There's some jethro wisdom in case it speeds thigns up: 

Link; https://github.com/eastgenomics/eggd_tso500/blob/ae5633715754453ea8c001cc5b5f38434679330e/src/code.sh#L61
</blockquote></details>

The download-all-inputs bit is fairly small. It's the uploading of outputs from the cnv_calling that takes time (although not as much as before, thanks to Jethro)
___
*[`src/GATK_gCNVcaller.sh` line 263 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OY0iK2QVjtUCoBMkD:-O0mkkep24XaD8WhpFvZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L263)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could you add this directly to the download command?
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 268 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OY9Jc8Uz4cn5bgXbB:-O0mklMb8qZ7OwZ8qZ4V:bsmsvl7) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L268)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

as above, could the ploidy directory be mkdir -p /home/dnanexus/in/ploidy-dir then download directly in there? 
How big are they files? Should it be parallelised at all?
</blockquote></details>

Download only takes a couple of minutes so no need to parallelise, but removed the mv
___
*[`src/GATK_gCNVcaller.sh` line 297 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0OYlgz2cwEDu9KWIBB:-O0mppfiEeDUvLVueFk6:b-kjrh6q) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L297)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

does this space here work?
</blockquote></details>

space?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 6 of 8 files reviewed, 11 unresolved discussions (waiting on @Addy81, @chrispyatt, and @mattgarner)

___
*[`dxapp.json` line 144 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PQM1T2dsz_vDptQLo:-O1uqcX_7mKVNSKrCbPz:bdovshv) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L144)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

priority isn't a used key in the `dxapp.json` it wants to be `"headJobOnDemand": true`
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Igk3hDpMXvMNaURyk:-O0nEOP_0ydA2OZBvlUw:bb6mt9b) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L142)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Deferring this until I've checked whether breakpoint spanning CNVs are affected
</blockquote></details>

:+1:

**Review by chrispyatt — COMMENTED** [review]
.whl files should be addressed now

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-:-O248KTi0q4hGKq3nD64:bvh4bcy)* status: 6 of 8 files reviewed, 11 unresolved discussions (waiting on @Addy81, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 144 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0PQM1T2dsz_vDptQLo:-O248Zpi7sWTi1nXkk1k:b-886gsx) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/dxapp.json#L144)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

priority isn't a used key in the `dxapp.json` it wants to be `"headJobOnDemand": true`
</blockquote></details>

Fixed
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15#-O0Igk3hDpMXvMNaURyk:-O2493d77KboxLPeRkNZ:bidg9by) ([raw file](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/32b9cfed6aef3f9ba7be4b75e07c94c609b9c55e/src/GATK_gCNVcaller.sh#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

I've added something to choose bigger instances for bigger intervals files which should sort this.

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_GATKgCNV_call/15)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @Addy81 and @mattgarner)

**Comment by jethror1** [comment]
closing as superseded by #19

**Pull request closed without merging**
